# Generated by Django 3.0.3 on 2020-02-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisements',
            old_name='area',
            new_name='size',
        ),
    ]
