# Generated by Django 3.0.2 on 2020-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0002_auto_20200222_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='slug',
            field=models.SlugField(),
        ),
    ]
