# Generated by Django 3.0.2 on 2020-02-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0003_auto_20200222_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
