# Generated by Django 3.0.3 on 2020-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0009_auto_20200227_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(blank=True, upload_to='house_pics'),
        ),
    ]
