# Generated by Django 3.0.3 on 2020-02-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0010_auto_20200228_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(upload_to='house_pics'),
        ),
    ]
