# Generated by Django 3.0.3 on 2020-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0014_auto_20200228_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='number',
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='defaulthouse.jpg', upload_to='house_pics'),
        ),
    ]
