# Generated by Django 3.0.3 on 2020-02-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0016_auto_20200228_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='defaulthouse.jpg', upload_to='house_pics/'),
        ),
    ]
