# Generated by Django 3.0.3 on 2020-02-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0017_auto_20200228_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='slug',
        ),
    ]
