# Generated by Django 3.0.3 on 2020-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BariVara', '0019_auto_20200312_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='defaulthouse.jpg', upload_to='house_pics/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
